@extends('layouts.frontend')

@section('title', 'Terms of Service — HealthIntel')
@section('description', 'HealthIntel terms of service. By using HealthIntel, you agree to these terms.')
@section('robots', 'noindex, follow')

@section('content')
<section class="section">
    <div class="wrap">
        <div class="section-header center">
            <span class="eyebrow">Legal</span>
            <h1>Terms of Service</h1>
            <p>Last updated: {{ date('F d, Y') }}</p>
        </div>

        <div class="page-section" style="margin:0 auto">

            <!-- Overview -->
            <div style="background:var(--surface);border:1px solid var(--line);border-radius:16px;padding:28px;margin-bottom:36px">
                <h2 style="margin-top:0">Agreement Overview</h2>
                <p style="margin-bottom:0">Welcome to <strong>HealthIntel</strong> ("the Service", "the Platform", "we", "us", "our"), operated from <strong>healthintel.app</strong>. By accessing or using HealthIntel — whether via our website, mobile application (Android APK), or API — you ("you", "your", "User") agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
            </div>

            <!-- 1. Medical Disclaimer -->
            <h2>1. Medical Disclaimer — PLEASE READ CAREFULLY</h2>

            <div style="background:#FFF7ED;border:2px solid #F97316;border-radius:12px;padding:24px;margin:20px 0">
                <p style="margin:0;font-size:1.05rem;font-weight:700;color:#9A3412">⚠️ HealthIntel is NOT a medical device, diagnostic tool, or healthcare provider.</p>
            </div>

            <ul>
                <li><strong>Educational purpose only:</strong> All lab result interpretations, symptom suggestions, and health insights generated by HealthIntel are for <strong>educational and informational purposes only</strong>. They are not medical diagnoses, treatment recommendations, or prescriptions.</li>
                <li><strong>AI-generated content:</strong> Our interpretations are produced by artificial intelligence (DeepSeek AI). AI can make mistakes. Results may be incomplete, inaccurate, or misleading. <strong>Never rely solely on AI-generated health information for medical decisions.</strong></li>
                <li><strong>Not a doctor-patient relationship:</strong> Using HealthIntel does not create a doctor-patient, therapist-client, or any other professional healthcare relationship. We do not employ medical professionals to review AI outputs.</li>
                <li><strong>Emergency warning:</strong> If you are experiencing a medical emergency, call your local emergency number immediately (Nigeria: 112 or 767). Do not use HealthIntel for emergency situations.</li>
                <li><strong>Consult a professional:</strong> Always consult a <strong>licensed healthcare professional</strong> for: interpretation of your lab results, diagnosis of any condition, treatment decisions, medication changes, and any health concerns. Share HealthIntel's AI interpretations with your doctor — do not use them as a substitute for professional consultation.</li>
                <li><strong>Lab result accuracy:</strong> We do not verify the accuracy of lab values you enter or upload. The quality of AI interpretations depends entirely on the accuracy of the data you provide. Entering incorrect values will produce incorrect interpretations.</li>
            </ul>

            <!-- 2. Eligibility & Account -->
            <h2>2. Eligibility & Account Registration</h2>
            <ul>
                <li><strong>Age requirement:</strong> You must be at least <strong>16 years old</strong> to create an account. Users under 16 require verifiable parental or guardian consent.</li>
                <li><strong>Accurate information:</strong> You agree to provide true, accurate, and complete information during registration and when entering health data. Using false information (especially health data that affects AI interpretations) may result in inaccurate results for which we bear no liability.</li>
                <li><strong>One account per person:</strong> You may not create multiple accounts to obtain additional signup credits or circumvent usage limits.</li>
                <li><strong>Account security:</strong> You are responsible for maintaining the confidentiality of your login credentials. Notify us immediately at <a href="mailto:hello@healthintel.app">hello@healthintel.app</a> if you suspect unauthorised access.</li>
                <li><strong>Account sharing:</strong> Your account is personal. Do not share your login credentials with others or allow others to use your account.</li>
                <li><strong>Right to refuse service:</strong> We reserve the right to suspend or terminate accounts that violate these Terms, at our sole discretion, without prior notice.</li>
            </ul>

            <!-- 3. Credits System -->
            <h2>3. Credits & Pricing</h2>

            <h3 style="font-size:1rem;margin-top:20px">3.1 How Credits Work</h3>
            <p>HealthIntel operates on a <strong>credit-based system</strong>. Certain actions consume credits from your account balance:</p>

            <div style="overflow-x:auto">
            <table style="width:100%;border-collapse:collapse;font-size:0.92rem;margin:16px 0 24px">
                <thead>
                    <tr style="background:var(--surface);text-align:left">
                        <th style="padding:10px 16px;border:1px solid var(--line)">Action</th>
                        <th style="padding:10px 16px;border:1px solid var(--line)">Credits Required</th>
                        <th style="padding:10px 16px;border:1px solid var(--line)">Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="padding:10px 16px;border:1px solid var(--line);font-weight:600">Lab Result Interpretation</td>
                        <td style="padding:10px 16px;border:1px solid var(--line)">2 credits</td>
                        <td style="padding:10px 16px;border:1px solid var(--line)">Per test panel submitted (manual entry of individual test values)</td>
                    </tr>
                    <tr>
                        <td style="padding:10px 16px;border:1px solid var(--line);font-weight:600">PDF Lab Report Interpretation</td>
                        <td style="padding:10px 16px;border:1px solid var(--line)">3 credits</td>
                        <td style="padding:10px 16px;border:1px solid var(--line)">Per PDF lab report uploaded for AI analysis</td>
                    </tr>
                    <tr>
                        <td style="padding:10px 16px;border:1px solid var(--line);font-weight:600">Symptom Checker</td>
                        <td style="padding:10px 16px;border:1px solid var(--line)">1 credit</td>
                        <td style="padding:10px 16px;border:1px solid var(--line)">Per symptom check query (suggests relevant lab test panels)</td>
                    </tr>
                </tbody>
            </table>
            </div>

            <h3 style="font-size:1rem">3.2 Earning Credits</h3>
            <ul>
                <li><strong>Signup bonus:</strong> New users receive <strong>3 free credits</strong> upon registration (one-time only). Credit values are subject to change; the current bonus is configurable in the admin panel.</li>
                <li><strong>Admin grants:</strong> Platform administrators may grant additional credits at their discretion (e.g., for promotions, compensations, or loyalty rewards).</li>
            </ul>

            <h3 style="font-size:1rem">3.3 Purchasing Credits</h3>
            <ul>
                <li><strong>Credit packages:</strong> Additional credits may be purchased in packages. Package prices and credit amounts are displayed at the time of purchase and are subject to change.</li>
                <li><strong>Payment processing:</strong> Payments are processed securely through <strong>Paystack</strong> (primary) or <strong>Flutterwave</strong> (optional, enabled at admin discretion). Both are PCI-DSS Level 1 certified. We do not store your card details.</li>
                <li><strong>Currency:</strong> All prices are denominated in <strong>Nigerian Naira (NGN)</strong>. International users may incur currency conversion fees from their bank.</li>
                <li><strong>Taxes:</strong> Prices displayed include applicable VAT where required by Nigerian law.</li>
            </ul>

            <h3 style="font-size:1rem">3.4 Refund Policy</h3>
            <ul>
                <li><strong>Credits are non-refundable:</strong> Purchased credits are generally non-refundable once the transaction is complete. By purchasing credits, you acknowledge that you are buying a <strong>digital service that is delivered immediately</strong> (credits are added to your account instantly upon successful payment).</li>
                <li><strong>Exceptions:</strong> Refunds may be issued in the following circumstances:
                    <ul>
                        <li><strong>Duplicate charge:</strong> If you are charged twice for the same transaction due to a technical error</li>
                        <li><strong>Service unavailability:</strong> If the AI interpretation service is completely unavailable for more than 48 consecutive hours and you have unused purchased credits</li>
                        <li><strong>Legal requirement:</strong> Where Nigerian consumer protection law mandates a refund</li>
                    </ul>
                </li>
                <li><strong>Refund process:</strong> To request a refund, email <a href="mailto:hello@healthintel.app">hello@healthintel.app</a> with your account email, transaction reference, and reason. We will respond within 5 business days.</li>
                <li><strong>Signup bonus credits:</strong> Free credits have no monetary value and are not refundable.</li>
            </ul>

            <h3 style="font-size:1rem">3.5 Credit Expiration</h3>
            <ul>
                <li><strong>Purchased credits:</strong> Do not expire while your account remains active.</li>
                <li><strong>Inactive accounts:</strong> We reserve the right to expire credits on accounts that have been completely inactive (no logins) for 24 consecutive months, with 30 days prior notice via email.</li>
                <li><strong>Account termination:</strong> Credits are forfeited upon account termination for violation of these Terms.</li>
            </ul>

            <!-- 4. Service Description -->
            <h2>4. Description of Services</h2>
            <p>HealthIntel provides the following features (collectively, "the Service"):</p>

            <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px;margin:20px 0">
                <div style="background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:20px">
                    <strong style="color:var(--primary)">🧪 Lab Result Interpreter</strong>
                    <p style="margin:8px 0 0;font-size:0.9rem">Enter your lab test values manually or upload a PDF lab report. Our AI generates a plain-language interpretation with flag explanations, reference ranges, and suggested next steps.</p>
                </div>
                <div style="background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:20px">
                    <strong style="color:var(--primary)">🔍 Symptom Checker</strong>
                    <p style="margin:8px 0 0;font-size:0.9rem">Describe your symptoms and get AI-suggested lab test panels that may help identify the cause. This is a guidance tool — not a diagnosis.</p>
                </div>
                <div style="background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:20px">
                    <strong style="color:var(--primary)">📊 Health Trackers</strong>
                    <p style="margin:8px 0 0;font-size:0.9rem">Log daily health metrics: blood pressure, blood glucose, weight, sleep, water intake, and exercise. Monitor trends over time — entirely voluntary and self-reported.</p>
                </div>
                <div style="background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:20px">
                    <strong style="color:var(--primary)">🏥 Provider Directory</strong>
                    <p style="margin:8px 0 0;font-size:0.9rem">Browse a directory of healthcare providers in Nigeria. Provider listings are sourced from public directories and partner submissions. We do not endorse any specific provider.</p>
                </div>
                <div style="background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:20px">
                    <strong style="color:var(--primary)">🛡️ Insurance/HMO Comparison</strong>
                    <p style="margin:8px 0 0;font-size:0.9rem">Compare health insurance and HMO plans in Nigeria. Information is provided for reference only and may not be current. Verify directly with the insurer.</p>
                </div>
                <div style="background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:20px">
                    <strong style="color:var(--primary)">📅 Appointments</strong>
                    <p style="margin:8px 0 0;font-size:0.9rem">Schedule and manage healthcare appointments with optional reminders. We do not facilitate the actual appointment — this is a personal scheduling tool.</p>
                </div>
            </div>

            <!-- 5. Acceptable Use -->
            <h2>5. Acceptable Use Policy</h2>
            <p>You agree <strong>not</strong> to:</p>
            <ul>
                <li><strong>Illegal use:</strong> Use the Service for any unlawful purpose or in violation of any Nigerian federal, state, or local law or regulation</li>
                <li><strong>Abuse the AI:</strong> Submit excessive or automated requests, attempt to extract the AI model, reverse-engineer prompts, or use the Service to train competing AI models</li>
                <li><strong>Harmful content:</strong> Upload files containing malware, viruses, or any code intended to damage or interfere with the Service</li>
                <li><strong>Impersonation:</strong> Impersonate any person or entity, or falsely state or misrepresent your affiliation with a person or entity</li>
                <li><strong>Circumvention:</strong> Attempt to bypass our credit system, rate limits, or security measures</li>
                <li><strong>Unauthorised access:</strong> Attempt to gain unauthorised access to our systems, user accounts, or data (including scraping, crawling, or automated data extraction beyond normal API usage)</li>
                <li><strong>Interference:</strong> Interfere with or disrupt the Service, servers, or networks connected to the Service</li>
                <li><strong>Resale:</strong> Resell, sublicense, or commercially exploit the Service or AI interpretations without explicit written permission</li>
                <li><strong>Misinformation:</strong> Use the Service to generate, spread, or legitimise health misinformation or fraudulent medical claims</li>
                <li><strong>Minors' data:</strong> Upload health data of children under 16 without verifiable parental consent</li>
            </ul>

            <!-- 6. Intellectual Property -->
            <h2>6. Intellectual Property</h2>
            <ul>
                <li><strong>Our IP:</strong> The HealthIntel name, logo, branding, website design, mobile app UI, source code, database schema, AI prompt engineering, and original content are the <strong>exclusive intellectual property of HealthIntel</strong>. All rights reserved.</li>
                <li><strong>Your data:</strong> You retain full ownership of the health data, lab results, and personal information you upload or enter. We claim no ownership over your health data. You grant us a limited, worldwide, royalty-free license to use your data solely as necessary to provide the Service to you (e.g., sending lab values to the AI for interpretation). See our <a href="{{ route('privacy') }}">Privacy Policy</a> for details.</li>
                <li><strong>AI output:</strong> The AI-generated interpretation text is produced by a third-party AI model (DeepSeek). We do not claim copyright ownership over AI-generated text. You may freely share your AI interpretations with your healthcare providers.</li>
                <li><strong>Feedback:</strong> If you submit suggestions, ideas, or feedback about the Service, you grant us a perpetual, irrevocable, royalty-free license to use that feedback to improve the Service without compensation.</li>
                <li><strong>Trademarks:</strong> Paystack® and Flutterwave® are registered trademarks of their respective owners. DeepSeek® is a trademark of DeepSeek. Use of these names does not imply endorsement.</li>
            </ul>

            <!-- 7. Third-Party Services -->
            <h2>7. Third-Party Services & Links</h2>
            <ul>
                <li><strong>AI provider:</strong> Lab interpretations are generated using <strong>DeepSeek's API</strong>. We are not responsible for the accuracy, availability, or content of DeepSeek's service. If DeepSeek's API is unavailable, interpretations will fail gracefully with an error message.</li>
                <li><strong>Payment processors:</strong> Payments are handled by <strong>Paystack</strong> and <strong>Flutterwave</strong>. Their respective terms of service and privacy policies apply to payment transactions. Disputes regarding payment processing should be directed to the relevant payment provider.</li>
                <li><strong>External links:</strong> The Provider Directory and Insurance Comparison features may include links to third-party websites. We are not responsible for the content, accuracy, or practices of any third-party website. Following external links is at your own risk.</li>
                <li><strong>No endorsement:</strong> Listing a healthcare provider or insurance plan in our directory does not constitute endorsement, recommendation, or verification of their qualifications.</li>
            </ul>

            <!-- 8. Service Availability -->
            <h2>8. Service Availability & Modifications</h2>
            <ul>
                <li><strong>No uptime guarantee:</strong> We strive to maintain high availability but do not guarantee uninterrupted access. The Service may be unavailable during maintenance, updates, or unforeseen technical issues.</li>
                <li><strong>Feature changes:</strong> We reserve the right to modify, suspend, or discontinue any feature of the Service at any time, with or without notice. Material changes will be communicated via email or in-app notification.</li>
                <li><strong>Credit costs:</strong> The credit cost of actions (e.g., 2 credits per lab interpretation) may change. We will provide at least 14 days notice before price increases via email and the website.</li>
                <li><strong>Regional availability:</strong> HealthIntel is designed for users in Nigeria and may not be optimised for other regions. Lab reference ranges are based on Nigerian and general population standards.</li>
            </ul>

            <!-- 9. Limitation of Liability -->
            <h2>9. Limitation of Liability</h2>

            <div style="background:#FFF7ED;border:2px solid #F97316;border-radius:12px;padding:24px;margin:20px 0">
                <p style="margin:0;font-size:0.95rem;color:#9A3412"><strong>IMPORTANT:</strong> HealthIntel provides AI-generated educational content. We are not healthcare providers. The following limitations apply to the fullest extent permitted by Nigerian law.</p>
            </div>

            <ul>
                <li><strong>No liability for health decisions:</strong> HealthIntel and its owners, employees, and agents shall <strong>NOT</strong> be held liable for any:
                    <ul>
                        <li>Medical decisions made based on AI interpretations</li>
                        <li>Misdiagnosis, delayed diagnosis, or failure to diagnose</li>
                        <li>Health deterioration, injury, or death resulting from reliance on our content</li>
                        <li>Adverse drug reactions or interactions identified or missed by AI analysis</li>
                        <li>Incorrect lab value entry leading to inaccurate interpretations</li>
                    </ul>
                </li>
                <li><strong>Service interruptions:</strong> We are not liable for any damages resulting from Service unavailability, data loss, or technical errors.</li>
                <li><strong>Indirect damages:</strong> To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to: loss of profits, loss of data, emotional distress, or reputational harm.</li>
                <li><strong>Cap on liability:</strong> Our total liability for any claim arising from use of the Service shall not exceed the <strong>total amount you paid us for credits in the 12 months preceding the claim</strong>, or ₦50,000 (fifty thousand Naira), whichever is lower.</li>
                <li><strong>AI limitations:</strong> AI models can produce incorrect, biased, or harmful outputs. We implement guardrails (strict prompts, disclaimer requirements) but cannot guarantee that every AI output will be safe, accurate, or appropriate. You assume all risks associated with relying on AI-generated health information.</li>
                <li><strong>Third-party providers:</strong> We are not liable for the actions, errors, or omissions of DeepSeek, Paystack, Flutterwave, or any healthcare provider listed in our directory.</li>
            </ul>

            <!-- 10. Indemnification -->
            <h2>10. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless <strong>HealthIntel</strong>, its owners, directors, employees, contractors, and agents from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising from:</p>
            <ul>
                <li>Your use of the Service or reliance on AI-generated interpretations</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any third-party rights, including privacy or intellectual property rights</li>
                <li>Your violation of any applicable Nigerian law or regulation</li>
                <li>Health data you enter that belongs to another person without their consent</li>
            </ul>

            <!-- 11. Termination -->
            <h2>11. Termination</h2>
            <ul>
                <li><strong>By you:</strong> You may terminate your account at any time through the app settings or by contacting us. Upon termination, your account data will be deleted in accordance with our <a href="{{ route('privacy') }}">Privacy Policy</a>.</li>
                <li><strong>By us:</strong> We may suspend or terminate your account immediately, without prior notice or liability, if you breach these Terms, engage in fraudulent activity, or abuse the Service. We will make reasonable efforts to notify you via email.</li>
                <li><strong>Effect of termination:</strong>
                    <ul>
                        <li>Your right to access the Service ceases immediately</li>
                        <li>Remaining credits are forfeited (except where termination is due to our Service discontinuation, in which case we will provide a pro-rata refund for purchased credits)</li>
                        <li>Provisions that by their nature should survive termination (Medical Disclaimer, Limitation of Liability, Indemnification, Intellectual Property, Governing Law) shall survive</li>
                    </ul>
                </li>
                <li><strong>Data after termination:</strong> We will delete your personal data in accordance with our Privacy Policy. Payment records may be retained as required by Nigerian financial regulations.</li>
            </ul>

            <!-- 12. Governing Law -->
            <h2>12. Governing Law & Dispute Resolution</h2>
            <ul>
                <li><strong>Governing law:</strong> These Terms shall be governed by and construed in accordance with the laws of the <strong>Federal Republic of Nigeria</strong>, without regard to conflict of law principles.</li>
                <li><strong>Jurisdiction:</strong> Any legal action arising from these Terms shall be brought exclusively in the competent courts of <strong>Lagos State, Nigeria</strong>.</li>
                <li><strong>Informal resolution:</strong> Before initiating formal legal proceedings, you agree to first contact us at <a href="mailto:hello@healthintel.app">hello@healthintel.app</a> to attempt to resolve the dispute informally. We will work in good faith to resolve the issue within 30 days.</li>
                <li><strong>Arbitration:</strong> If informal resolution fails, disputes shall be resolved through <strong>binding arbitration</strong> in Lagos, Nigeria, under the Arbitration and Conciliation Act, Cap A18, Laws of the Federation of Nigeria 2004. The arbitration shall be conducted by a single arbitrator mutually agreed upon by both parties.</li>
                <li><strong>Class action waiver:</strong> You agree to resolve disputes with us on an individual basis. You waive any right to participate in a class action lawsuit or class-wide arbitration.</li>
            </ul>

            <!-- 13. Changes -->
            <h2>13. Changes to These Terms</h2>
            <ul>
                <li><strong>Notification:</strong> We reserve the right to modify these Terms at any time. For material changes, we will:
                    <ul>
                        <li>Post the updated Terms on this page with a new "Last updated" date</li>
                        <li>Send an email notification to registered users at least <strong>14 days</strong> before the changes take effect</li>
                        <li>Display an in-app notice the next time you open the mobile app</li>
                    </ul>
                </li>
                <li><strong>Acceptance:</strong> Your continued use of HealthIntel after the effective date constitutes acceptance of the updated Terms. If you do not agree, you must stop using the Service and delete your account before the changes take effect.</li>
                <li><strong>Non-material changes:</strong> Minor changes (typo fixes, formatting, clarifications) may be made without advance notice.</li>
            </ul>

            <!-- 14. Contact -->
            <h2>14. Contact Us</h2>
            <p>For questions about these Terms, account issues, refund requests, or legal inquiries:</p>
            <div style="background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:24px;margin-top:16px">
                <p style="margin:0"><strong>Email:</strong> <a href="mailto:hello@healthintel.app">hello@healthintel.app</a></p>
                <p style="margin:8px 0 0"><strong>Legal / DPO:</strong> <a href="mailto:privacy@healthintel.app">privacy@healthintel.app</a></p>
                <p style="margin:8px 0 0"><strong>Response time:</strong> We aim to respond to all inquiries within 48 hours.</p>
                <p style="margin:8px 0 0"><strong>Website:</strong> <a href="https://healthintel.app" target="_blank">healthintel.app</a></p>
            </div>

        </div>
    </div>
</section>
@endsection