<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Batch Lab Results Interpretation</title>
    <style>
        body { font-family: 'DejaVu Sans', Arial, sans-serif; color: #1B2622; line-height: 1.6; font-size: 11pt; }
        .header { border-bottom: 2px solid {{ $brand_color }}; padding-bottom: 16px; margin-bottom: 24px; }
        .header-content { display: flex; align-items: center; gap: 16px; }
        .logo-placeholder { font-size: 18pt; font-weight: bold; color: {{ $brand_color }}; }
        .provider-name { font-size: 16pt; font-weight: bold; }
        .provider-contact { font-size: 9pt; color: #57645D; }
        .meta { background: #F4F6F3; border-radius: 8px; padding: 12px 16px; margin-bottom: 24px; font-size: 9pt; }
        .meta-row { display: flex; justify-content: space-between; }
        .meta-label { color: #57645D; }
        .meta-value { font-weight: 600; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        th { background: {{ $brand_color }}15; padding: 10px 12px; text-align: left; font-size: 9pt; font-weight: 600; color: {{ $brand_color }}; border-bottom: 2px solid {{ $brand_color }}30; }
        td { padding: 10px 12px; font-size: 10pt; border-bottom: 1px solid #DCE3DE; }
        .badge { display: inline-block; padding: 3px 8px; border-radius: 10px; font-size: 7pt; font-weight: bold; }
        .badge-normal { background: #DCFCE7; color: #166534; }
        .badge-low { background: #FEF3C7; color: #92400E; }
        .badge-high { background: #FEE2E2; color: #991B1B; }
        .badge-unknown { background: #E5E7EB; color: #4B5563; }
        .interpretation { font-size: 9pt; color: #57645D; line-height: 1.5; max-width: 300px; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #DCE3DE; font-size: 8pt; color: #57645D; }
        .powered-by { font-size: 7pt; color: #A0AEA7; text-align: center; margin-top: 8px; }
        .disclaimer { margin-top: 16px; padding: 12px; background: #FFF7ED; border: 1px solid #FFEDD5; border-radius: 6px; font-size: 8pt; color: #92400E; }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            @if($brand_logo)
                <img src="{{ $brand_logo }}" style="max-width: 140px; max-height: 60px;" alt="Logo">
            @else
                <div class="logo-placeholder">{{ $provider->name }}</div>
            @endif
            <div>
                <div class="provider-name">{{ $is_white_label ? $provider->name : 'HealthIntel' }}</div>
                <div class="provider-contact">{{ $brand_contact }}</div>
            </div>
        </div>
    </div>

    <div class="meta">
        <div class="meta-row">
            <span><span class="meta-label">Patient ID:</span> <span class="meta-value">{{ $patient_id }}</span></span>
            <span><span class="meta-label">Provider:</span> <span class="meta-value">{{ $provider->name }}</span></span>
        </div>
        <div class="meta-row" style="margin-top:6px">
            <span><span class="meta-label">Tests:</span> <span class="meta-value">{{ count($items) }} results</span></span>
            <span><span class="meta-label">Generated:</span> <span class="meta-value">{{ $generated_at }}</span></span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Test</th>
                <th>Result</th>
                <th>Normal Range</th>
                <th>Status</th>
                <th>Interpretation</th>
            </tr>
        </thead>
        <tbody>
            @foreach($items as $item)
            <tr>
                <td><strong>{{ $item['test_name'] }}</strong></td>
                <td>{{ $item['value'] }} {{ $item['unit'] }}</td>
                <td>{{ $item['range'] }}</td>
                <td>
                    <span class="badge badge-{{ $item['status_indicator'] }}">
                        {{ strtoupper($item['status_indicator']) }}
                    </span>
                </td>
                <td class="interpretation">{{ $item['interpretation_text'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="disclaimer">
        <strong>Medical Disclaimer:</strong> These interpretations are for informational purposes only and do not constitute medical advice. They are generated by an AI-assisted system and have not been reviewed by a physician. Always consult a qualified healthcare provider for diagnosis and treatment decisions.
    </div>

    <div class="footer">
        <div>{{ $provider->name }} | {{ $brand_contact }}</div>
        @if(!$is_white_label)
            <div class="powered-by">Powered by HealthIntel — Your health, decoded.</div>
        @endif
    </div>
</body>
</html>